export const elements = [
	{
		number: 1,
		symbol: 'H',
		name: 'Hydrogen',
		atomicMass: 1.008,
		row: 1,
		column: 1,
		subshellBlock: 's',
		cpkHexColor: 'FFFFFF',
		electronicConfiguration: '1s1',
		standardState: 'gas',
		chemicalFamily: 'nonmetal',
		metallicity: 'nonmetal',
		ionizationEnergy: 13.5984,
		valence: 1,
		electronegativity: 2.20,
	},
	{
		number: 2,
		symbol: 'He',
		name: 'Helium',
		atomicMass: 4.002602,
		row: 1,
		column: 18,
		subshellBlock: 's',
		cpkHexColor: 'D9FFFF',
		electronicConfiguration: '1s2',
		standardState: 'gas',
		chemicalFamily: 'noble-gas',
		metallicity: 'nonmetal',
		ionizationEnergy: 24.5874,
		valence: 2,
		electronegativity: null,
	},
	{
		number: 3,
		symbol: 'Li',
		name: 'Lithium',
		atomicMass: 6.94,
		row: 2,
		column: 1,
		subshellBlock: 's',
		cpkHexColor: 'CC80FF',
		electronicConfiguration: '[He] 2s1',
		standardState: 'solid',
		chemicalFamily: 'alkali-metal',
		metallicity: 'metal',
		ionizationEnergy: 5.3917,
		valence: 1,
		electronegativity: 0.98,
	},
	{
		number: 4,
		symbol: 'Be',
		name: 'Beryllium',
		atomicMass: 9.0121831,
		row: 2,
		column: 2,
		subshellBlock: 's',
		cpkHexColor: 'C2FF00',
		electronicConfiguration: '[He] 2s2',
		standardState: 'solid',
		chemicalFamily: 'alkaline-earth-metal',
		metallicity: 'metal',
		ionizationEnergy: 9.3227,
		valence: 2,
		electronegativity: 1.57,
	},
	{
		number: 5,
		symbol: 'B',
		name: 'Boron',
		atomicMass: 10.81,
		row: 2,
		column: 13,
		subshellBlock: 'p',
		cpkHexColor: 'FFB5B5',
		electronicConfiguration: '[He] 2s2 2p1',
		standardState: 'solid',
		chemicalFamily: 'metalloid',
		metallicity: 'metalloid',
		ionizationEnergy: 8.298,
		valence: 3,
		electronegativity: 2.04,
	},
	{
		number: 6,
		symbol: 'C',
		name: 'Carbon',
		atomicMass: 12.011,
		row: 2,
		column: 14,
		subshellBlock: 'p',
		cpkHexColor: 909090,
		electronicConfiguration: '[He] 2s2 2p2',
		standardState: 'solid',
		chemicalFamily: 'nonmetal',
		metallicity: 'nonmetal',
		ionizationEnergy: 11.2603,
		valence: 4,
		electronegativity: 2.55,
	},
	{
		number: 7,
		symbol: 'N',
		name: 'Nitrogen',
		atomicMass: 14.007,
		row: 2,
		column: 15,
		subshellBlock: 'p',
		cpkHexColor: '3050F8',
		electronicConfiguration: '[He] 2s2 2p3',
		standardState: 'gas',
		chemicalFamily: 'nonmetal',
		metallicity: 'nonmetal',
		ionizationEnergy: 14.5341,
		valence: 5,
		electronegativity: 3.04,
	},
	{
		number: 8,
		symbol: 'O',
		name: 'Oxygen',
		atomicMass: 15.999,
		row: 2,
		column: 16,
		subshellBlock: 'p',
		cpkHexColor: 'FF0D0D',
		electronicConfiguration: '[He] 2s2 2p4',
		standardState: 'gas',
		chemicalFamily: 'nonmetal',
		metallicity: 'nonmetal',
		ionizationEnergy: 13.6181,
		valence: 6,
		electronegativity: 3.44,
	},
	{
		number: 9,
		symbol: 'F',
		name: 'Fluorine',
		atomicMass: 18.998403163,
		row: 2,
		column: 17,
		subshellBlock: 'p',
		cpkHexColor: '90E050',
		electronicConfiguration: '[He] 2s2 2p5',
		standardState: 'gas',
		chemicalFamily: 'halogen',
		metallicity: 'nonmetal',
		ionizationEnergy: 17.4228,
		valence: 7,
		electronegativity: 3.98,
	},
	{
		number: 10,
		symbol: 'Ne',
		name: 'Neon',
		atomicMass: 20.1797,
		row: 2,
		column: 18,
		subshellBlock: 'p',
		cpkHexColor: 'B3E3F5',
		electronicConfiguration: '[He] 2s2 2p6',
		standardState: 'gas',
		chemicalFamily: 'noble-gas',
		metallicity: 'nonmetal',
		ionizationEnergy: 21.5645,
		valence: 8,
		electronegativity: null,
	},
	{
		number: 11,
		symbol: 'Na',
		name: 'Sodium',
		atomicMass: 22.98976928,
		row: 3,
		column: 1,
		subshellBlock: 's',
		cpkHexColor: 'AB5CF2',
		electronicConfiguration: '[Ne] 3s1',
		standardState: 'solid',
		chemicalFamily: 'alkali-metal',
		metallicity: 'metal',
		ionizationEnergy: 5.1391,
		valence: 1,
		electronegativity: 0.93,
	},
	{
		number: 12,
		symbol: 'Mg',
		name: 'Magnesium',
		atomicMass: 24.305,
		row: 3,
		column: 2,
		subshellBlock: 's',
		cpkHexColor: '8AFF00',
		electronicConfiguration: '[Ne] 3s2',
		standardState: 'solid',
		chemicalFamily: 'alkaline-earth-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.6462,
		valence: 2,
		electronegativity: 1.31,
	},
	{
		number: 13,
		symbol: 'Al',
		name: 'Aluminum',
		atomicMass: 26.9815385,
		row: 3,
		column: 13,
		subshellBlock: 'p',
		cpkHexColor: 'BFA6A6',
		electronicConfiguration: '[Ne] 3s2 3p1',
		standardState: 'solid',
		chemicalFamily: 'metal',
		metallicity: 'metal',
		ionizationEnergy: 5.9858,
		valence: 3,
		electronegativity: 1.61,
	},
	{
		number: 14,
		symbol: 'Si',
		name: 'Silicon',
		atomicMass: 28.085,
		row: 3,
		column: 14,
		subshellBlock: 'p',
		cpkHexColor: 'F0C8A0',
		electronicConfiguration: '[Ne] 3s2 3p2',
		standardState: 'solid',
		chemicalFamily: 'metalloid',
		metallicity: 'metalloid',
		ionizationEnergy: 8.1517,
		valence: 4,
		electronegativity: 1.90,
	},
	{
		number: 15,
		symbol: 'P',
		name: 'Phosphorus',
		atomicMass: 30.973761998,
		row: 3,
		column: 15,
		subshellBlock: 'p',
		cpkHexColor: 'FF8000',
		electronicConfiguration: '[Ne] 3s2 3p3',
		standardState: 'solid',
		chemicalFamily: 'nonmetal',
		metallicity: 'nonmetal',
		ionizationEnergy: 10.4867,
		valence: 5,
		electronegativity: 2.19,
	},
	{
		number: 16,
		symbol: 'S',
		name: 'Sulfur',
		atomicMass: 32.06,
		row: 3,
		column: 16,
		subshellBlock: 'p',
		cpkHexColor: 'FFFF30',
		electronicConfiguration: '[Ne] 3s2 3p4',
		standardState: 'solid',
		chemicalFamily: 'nonmetal',
		metallicity: 'nonmetal',
		ionizationEnergy: 10.36,
		valence: 6,
		electronegativity: 2.58,
	},
	{
		number: 17,
		symbol: 'Cl',
		name: 'Chlorine',
		atomicMass: 35.45,
		row: 3,
		column: 17,
		subshellBlock: 'p',
		cpkHexColor: '1FF01F',
		electronicConfiguration: '[Ne] 3s2 3p5',
		standardState: 'gas',
		chemicalFamily: 'halogen',
		metallicity: 'nonmetal',
		ionizationEnergy: 12.9676,
		valence: 7,
		electronegativity: 3.16,
	},
	{
		number: 18,
		symbol: 'Ar',
		name: 'Argon',
		atomicMass: 39.9481,
		row: 3,
		column: 18,
		subshellBlock: 'p',
		cpkHexColor: '80D1E3',
		electronicConfiguration: '[Ne] 3s2 3p6',
		standardState: 'gas',
		chemicalFamily: 'noble-gas',
		metallicity: 'nonmetal',
		ionizationEnergy: 15.7596,
		valence: 8,
		electronegativity: null,
	},
	{
		number: 19,
		symbol: 'K',
		name: 'Potassium',
		atomicMass: 39.09831,
		row: 4,
		column: 1,
		subshellBlock: 's',
		cpkHexColor: '8F40D4',
		electronicConfiguration: '[Ar] 4s1',
		standardState: 'solid',
		chemicalFamily: 'alkali-metal',
		metallicity: 'metal',
		ionizationEnergy: 4.3407,
		valence: 1,
		electronegativity: 0.82,
	},
	{
		number: 20,
		symbol: 'Ca',
		name: 'Calcium',
		atomicMass: 40.0784,
		row: 4,
		column: 2,
		subshellBlock: 's',
		cpkHexColor: '3DFF00',
		electronicConfiguration: '[Ar] 4s2',
		standardState: 'solid',
		chemicalFamily: 'alkaline-earth-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.1132,
		valence: 2,
		electronegativity: 1.00,
	},
	{
		number: 21,
		symbol: 'Sc',
		name: 'Scandium',
		atomicMass: 44.9559085,
		row: 4,
		column: 3,
		subshellBlock: 'd',
		cpkHexColor: 'E6E6E6',
		electronicConfiguration: '[Ar] 3d1 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.5615,
		valence: 3,
		electronegativity: 1.36,
	},
	{
		number: 22,
		symbol: 'Ti',
		name: 'Titanium',
		atomicMass: 47.8671,
		row: 4,
		column: 4,
		subshellBlock: 'd',
		cpkHexColor: 'BFC2C7',
		electronicConfiguration: '[Ar] 3d2 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.8281,
		valence: 4,
		electronegativity: 1.54,
	},
	{
		number: 23,
		symbol: 'V',
		name: 'Vanadium',
		atomicMass: 50.94151,
		row: 4,
		column: 5,
		subshellBlock: 'd',
		cpkHexColor: 'A6A6AB',
		electronicConfiguration: '[Ar] 3d3 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.7462,
		valence: 5,
		electronegativity: 1.63,
	},
	{
		number: 24,
		symbol: 'Cr',
		name: 'Chromium',
		atomicMass: 51.99616,
		row: 4,
		column: 6,
		subshellBlock: 'd',
		cpkHexColor: '8A99C7',
		electronicConfiguration: '[Ar] 3d5 4s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.7665,
		valence: 6,
		electronegativity: 1.66,
	},
	{
		number: 25,
		symbol: 'Mn',
		name: 'Manganese',
		atomicMass: 54.9380443,
		row: 4,
		column: 7,
		subshellBlock: 'd',
		cpkHexColor: '9C7AC7',
		electronicConfiguration: '[Ar] 3d5 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.434,
		valence: 7,
		electronegativity: 1.55,
	},
	{
		number: 26,
		symbol: 'Fe',
		name: 'Iron',
		atomicMass: 55.8452,
		row: 4,
		column: 8,
		subshellBlock: 'd',
		cpkHexColor: 'E06633',
		electronicConfiguration: '[Ar] 3d6 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.9024,
		valence: 8,
		electronegativity: 1.83,
	},
	{
		number: 27,
		symbol: 'Co',
		name: 'Cobalt',
		atomicMass: 58.9331944,
		row: 4,
		column: 9,
		subshellBlock: 'd',
		cpkHexColor: 'F090A0',
		electronicConfiguration: '[Ar] 3d7 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.881,
		valence: 9,
		electronegativity: 1.88,
	},
	{
		number: 28,
		symbol: 'Ni',
		name: 'Nickel',
		atomicMass: 58.69344,
		row: 4,
		column: 10,
		subshellBlock: 'd',
		cpkHexColor: '50D050',
		electronicConfiguration: '[Ar] 3d8 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.6398,
		valence: 10,
		electronegativity: 1.91,
	},
	{
		number: 29,
		symbol: 'Cu',
		name: 'Copper',
		atomicMass: 63.5463,
		row: 4,
		column: 11,
		subshellBlock: 'd',
		cpkHexColor: 'C88033',
		electronicConfiguration: '[Ar] 3d10 4s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.7264,
		valence: 11,
		electronegativity: 1.90,
	},
	{
		number: 30,
		symbol: 'Zn',
		name: 'Zinc',
		atomicMass: 65.382,
		row: 4,
		column: 12,
		subshellBlock: 'd',
		cpkHexColor: '7D80B0',
		electronicConfiguration: '[Ar] 3d10 4s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 9.3942,
		valence: 2,
		electronegativity: 1.65,
	},
	{
		number: 31,
		symbol: 'Ga',
		name: 'Gallium',
		atomicMass: 69.7231,
		row: 4,
		column: 13,
		subshellBlock: 'p',
		cpkHexColor: 'C28F8F',
		electronicConfiguration: '[Ar] 3d10 4s2 4p1',
		standardState: 'solid',
		chemicalFamily: 'metal',
		metallicity: 'metal',
		ionizationEnergy: 5.9993,
		valence: 3,
		electronegativity: 1.81,
	},
	{
		number: 32,
		symbol: 'Ge',
		name: 'Germanium',
		atomicMass: 72.6308,
		row: 4,
		column: 14,
		subshellBlock: 'p',
		cpkHexColor: '668F8F',
		electronicConfiguration: '[Ar] 3d10 4s2 4p2',
		standardState: 'solid',
		chemicalFamily: 'metalloid',
		metallicity: 'metalloid',
		ionizationEnergy: 7.8994,
		valence: 4,
		electronegativity: 2.01,
	},
	{
		number: 33,
		symbol: 'As',
		name: 'Arsenic',
		atomicMass: 74.9215956,
		row: 4,
		column: 15,
		subshellBlock: 'p',
		cpkHexColor: 'BD80E3',
		electronicConfiguration: '[Ar] 3d10 4s2 4p3',
		standardState: 'solid',
		chemicalFamily: 'metalloid',
		metallicity: 'metalloid',
		ionizationEnergy: 9.7886,
		valence: 5,
		electronegativity: 2.18,
	},
	{
		number: 34,
		symbol: 'Se',
		name: 'Selenium',
		atomicMass: 78.9718,
		row: 4,
		column: 16,
		subshellBlock: 'p',
		cpkHexColor: 'FFA100',
		electronicConfiguration: '[Ar] 3d10 4s2 4p4',
		standardState: 'solid',
		chemicalFamily: 'nonmetal',
		metallicity: 'nonmetal',
		ionizationEnergy: 9.7524,
		valence: 6,
		electronegativity: 2.55,
	},
	{
		number: 35,
		symbol: 'Br',
		name: 'Bromine',
		atomicMass: 79.904,
		row: 4,
		column: 17,
		subshellBlock: 'p',
		cpkHexColor: 'A62929',
		electronicConfiguration: '[Ar] 3d10 4s2 4p5',
		standardState: 'liquid',
		chemicalFamily: 'halogen',
		metallicity: 'nonmetal',
		ionizationEnergy: 11.8138,
		valence: 7,
		electronegativity: 2.96,
	},
	{
		number: 36,
		symbol: 'Kr',
		name: 'Krypton',
		atomicMass: 83.7982,
		row: 4,
		column: 18,
		subshellBlock: 'p',
		cpkHexColor: '5CB8D1',
		electronicConfiguration: '[Ar] 3d10 4s2 4p6',
		standardState: 'gas',
		chemicalFamily: 'noble-gas',
		metallicity: 'nonmetal',
		ionizationEnergy: 13.9996,
		valence: 8,
		electronegativity: null,
	},
	{
		number: 37,
		symbol: 'Rb',
		name: 'Rubidium',
		atomicMass: 85.46783,
		row: 5,
		column: 1,
		subshellBlock: 's',
		cpkHexColor: '702EB0',
		electronicConfiguration: '[Kr] 5s1',
		standardState: 'solid',
		chemicalFamily: 'alkali-metal',
		metallicity: 'metal',
		ionizationEnergy: 4.1771,
		valence: 1,
		electronegativity: 0.82,
	},
	{
		number: 38,
		symbol: 'Sr',
		name: 'Strontium',
		atomicMass: 87.621,
		row: 5,
		column: 2,
		subshellBlock: 's',
		cpkHexColor: '00FF00',
		electronicConfiguration: '[Kr] 5s2',
		standardState: 'solid',
		chemicalFamily: 'alkaline-earth-metal',
		metallicity: 'metal',
		ionizationEnergy: 5.6949,
		valence: 2,
		electronegativity: 0.95,
	},
	{
		number: 39,
		symbol: 'Y',
		name: 'Yttrium',
		atomicMass: 88.905842,
		row: 5,
		column: 3,
		subshellBlock: 'd',
		cpkHexColor: '94FFFF',
		electronicConfiguration: '[Kr] 4d1 5s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.2173,
		valence: 3,
		electronegativity: 1.22,
	},
	{
		number: 40,
		symbol: 'Zr',
		name: 'Zirconium',
		atomicMass: 91.2242,
		row: 5,
		column: 4,
		subshellBlock: 'd',
		cpkHexColor: '94E0E0',
		electronicConfiguration: '[Kr] 4d2 5s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.6339,
		valence: 4,
		electronegativity: 1.33,
	},
	{
		number: 41,
		symbol: 'Nb',
		name: 'Niobium',
		atomicMass: 92.906372,
		row: 5,
		column: 5,
		subshellBlock: 'd',
		cpkHexColor: '73C2C9',
		electronicConfiguration: '[Kr] 4d4 5s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.7589,
		valence: 5,
		electronegativity: 1.6,
	},
	{
		number: 42,
		symbol: 'Mo',
		name: 'Molybdenum',
		atomicMass: 95.951,
		row: 5,
		column: 6,
		subshellBlock: 'd',
		cpkHexColor: '54B5B5',
		electronicConfiguration: '[Kr] 4d5 5s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.0924,
		valence: 6,
		electronegativity: 2.16,
	},
	{
		number: 43,
		symbol: 'Tc',
		name: 'Technetium',
		atomicMass: 98,
		row: 5,
		column: 7,
		subshellBlock: 'd',
		cpkHexColor: '3B9E9E',
		electronicConfiguration: '[Kr] 4d5 5s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.28,
		valence: 7,
		electronegativity: 1.9,
	},
	{
		number: 44,
		symbol: 'Ru',
		name: 'Ruthenium',
		atomicMass: 101.072,
		row: 5,
		column: 8,
		subshellBlock: 'd',
		cpkHexColor: '248F8F',
		electronicConfiguration: '[Kr] 4d7 5s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.3605,
		valence: 8,
		electronegativity: 2.2,
	},
	{
		number: 45,
		symbol: 'Rh',
		name: 'Rhodium',
		atomicMass: 102.905502,
		row: 5,
		column: 9,
		subshellBlock: 'd',
		cpkHexColor: '0A7D8C',
		electronicConfiguration: '[Kr] 4d8 5s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.4589,
		valence: 9,
		electronegativity: 2.28,
	},
	{
		number: 46,
		symbol: 'Pd',
		name: 'Palladium',
		atomicMass: 106.421,
		row: 5,
		column: 10,
		subshellBlock: 'd',
		cpkHexColor: 6985,
		electronicConfiguration: '[Kr] 4d10',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 8.3369,
		valence: 10,
		electronegativity: 2.20,
	},
	{
		number: 47,
		symbol: 'Ag',
		name: 'Silver',
		atomicMass: 107.86822,
		row: 5,
		column: 11,
		subshellBlock: 'd',
		cpkHexColor: 'C0C0C0',
		electronicConfiguration: '[Kr] 4d10 5s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.5762,
		valence: 11,
		electronegativity: 1.93,
	},
	{
		number: 48,
		symbol: 'Cd',
		name: 'Cadmium',
		atomicMass: 112.4144,
		row: 5,
		column: 12,
		subshellBlock: 'd',
		cpkHexColor: 'FFD98F',
		electronicConfiguration: '[Kr] 4d10 5s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 8.9938,
		valence: 2,
		electronegativity: 1.69,
	},
	{
		number: 49,
		symbol: 'In',
		name: 'Indium',
		atomicMass: 114.8181,
		row: 5,
		column: 13,
		subshellBlock: 'p',
		cpkHexColor: 'A67573',
		electronicConfiguration: '[Kr] 4d10 5s2 5p1',
		standardState: 'solid',
		chemicalFamily: 'metal',
		metallicity: 'metal',
		ionizationEnergy: 5.7864,
		valence: 3,
		electronegativity: 1.78,
	},
	{
		number: 50,
		symbol: 'Sn',
		name: 'Tin',
		atomicMass: 118.7107,
		row: 5,
		column: 14,
		subshellBlock: 'p',
		cpkHexColor: 668080,
		electronicConfiguration: '[Kr] 4d10 5s2 5p2',
		standardState: 'solid',
		chemicalFamily: 'metal',
		metallicity: 'metal',
		ionizationEnergy: 7.3439,
		valence: 4,
		electronegativity: 1.96,
	},
	{
		number: 51,
		symbol: 'Sb',
		name: 'Antimony',
		atomicMass: 121.7601,
		row: 5,
		column: 15,
		subshellBlock: 'p',
		cpkHexColor: '9E63B5',
		electronicConfiguration: '[Kr] 4d10 5s2 5p3',
		standardState: 'solid',
		chemicalFamily: 'metalloid',
		metallicity: 'metalloid',
		ionizationEnergy: 8.6084,
		valence: 5,
		electronegativity: 2.05,
	},
	{
		number: 52,
		symbol: 'Te',
		name: 'Tellurium',
		atomicMass: 127.603,
		row: 5,
		column: 16,
		subshellBlock: 'p',
		cpkHexColor: 'D47A00',
		electronicConfiguration: '[Kr] 4d10 5s2 5p4',
		standardState: 'solid',
		chemicalFamily: 'metalloid',
		metallicity: 'metalloid',
		ionizationEnergy: 9.0096,
		valence: 6,
		electronegativity: 2.1,
	},
	{
		number: 53,
		symbol: 'I',
		name: 'Iodine',
		atomicMass: 126.904473,
		row: 5,
		column: 17,
		subshellBlock: 'p',
		cpkHexColor: 940094,
		electronicConfiguration: '[Kr] 4d10 5s2 5p5',
		standardState: 'solid',
		chemicalFamily: 'halogen',
		metallicity: 'nonmetal',
		ionizationEnergy: 10.4513,
		valence: 7,
		electronegativity: 2.66,
	},
	{
		number: 54,
		symbol: 'Xe',
		name: 'Xenon',
		atomicMass: 131.2936,
		row: 5,
		column: 18,
		subshellBlock: 'p',
		cpkHexColor: '429EB0',
		electronicConfiguration: '[Kr] 4d10 5s2 5p6',
		standardState: 'gas',
		chemicalFamily: 'noble-gas',
		metallicity: 'nonmetal',
		ionizationEnergy: 12.1298,
		valence: 8,
		electronegativity: null,
	},
	{
		number: 55,
		symbol: 'Cs',
		name: 'Cesium',
		atomicMass: 132.905451966,
		row: 6,
		column: 1,
		subshellBlock: 's',
		cpkHexColor: '57178F',
		electronicConfiguration: '[Xe] 6s1',
		standardState: 'solid',
		chemicalFamily: 'alkali-metal',
		metallicity: 'metal',
		ionizationEnergy: 3.8939,
		valence: 1,
		electronegativity: 0.79,
	},
	{
		number: 56,
		symbol: 'Ba',
		name: 'Barium',
		atomicMass: 137.3277,
		row: 6,
		column: 2,
		subshellBlock: 's',
		cpkHexColor: '00C900',
		electronicConfiguration: '[Xe] 6s2',
		standardState: 'solid',
		chemicalFamily: 'alkaline-earth-metal',
		metallicity: 'metal',
		ionizationEnergy: 5.2117,
		valence: 2,
		electronegativity: 0.89,
	},
	{
		number: 57,
		symbol: 'La',
		name: 'Lanthanum',
		atomicMass: 138.905477,
		row: 6,
		column: 3,
		subshellBlock: 'd',
		cpkHexColor: '70D4FF',
		electronicConfiguration: '[Xe] 5d1 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.5769,
		valence: 3,
		electronegativity: 1.10,
	},
	{
		number: 58,
		symbol: 'Ce',
		name: 'Cerium',
		atomicMass: 140.1161,
		row: 9,
		column: 4,
		subshellBlock: 'f',
		cpkHexColor: 'FFFFC7',
		electronicConfiguration: '[Xe] 4f1 5d1 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.5387,
		valence: 4,
		electronegativity: 1.12,
	},
	{
		number: 59,
		symbol: 'Pr',
		name: 'Praseodymium',
		atomicMass: 140.907662,
		row: 9,
		column: 5,
		subshellBlock: 'f',
		cpkHexColor: 'D9FFC7',
		electronicConfiguration: '[Xe] 4f3 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.473,
		valence: 5,
		electronegativity: 1.13,
	},
	{
		number: 60,
		symbol: 'Nd',
		name: 'Neodymium',
		atomicMass: 144.2423,
		row: 9,
		column: 6,
		subshellBlock: 'f',
		cpkHexColor: 'C7FFC7',
		electronicConfiguration: '[Xe] 4f4 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.525,
		valence: 6,
		electronegativity: 1.14,
	},
	{
		number: 61,
		symbol: 'Pm',
		name: 'Promethium',
		atomicMass: 145,
		row: 9,
		column: 7,
		subshellBlock: 'f',
		cpkHexColor: 'A3FFC7',
		electronicConfiguration: '[Xe] 4f5 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.582,
		valence: 7,
		electronegativity: 1.13,
	},
	{
		number: 62,
		symbol: 'Sm',
		name: 'Samarium',
		atomicMass: 150.362,
		row: 9,
		column: 8,
		subshellBlock: 'f',
		cpkHexColor: '8FFFC7',
		electronicConfiguration: '[Xe] 4f6 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.6437,
		valence: 8,
		electronegativity: 1.17,
	},
	{
		number: 63,
		symbol: 'Eu',
		name: 'Europium',
		atomicMass: 151.9641,
		row: 9,
		column: 9,
		subshellBlock: 'f',
		cpkHexColor: '61FFC7',
		electronicConfiguration: '[Xe] 4f7 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.6704,
		valence: 9,
		electronegativity: 1.2,
	},
	{
		number: 64,
		symbol: 'Gd',
		name: 'Gadolinium',
		atomicMass: 157.253,
		row: 9,
		column: 10,
		subshellBlock: 'f',
		cpkHexColor: '45FFC7',
		electronicConfiguration: '[Xe] 4f7 5d1 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 6.1501,
		valence: 10,
		electronegativity: 1.20,
	},
	{
		number: 65,
		symbol: 'Tb',
		name: 'Terbium',
		atomicMass: 158.925352,
		row: 9,
		column: 11,
		subshellBlock: 'f',
		cpkHexColor: '30FFC7',
		electronicConfiguration: '[Xe] 4f9 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.8638,
		valence: 11,
		electronegativity: 1.20,
	},
	{
		number: 66,
		symbol: 'Dy',
		name: 'Dysprosium',
		atomicMass: 162.5001,
		row: 9,
		column: 12,
		subshellBlock: 'f',
		cpkHexColor: '1FFFC7',
		electronicConfiguration: '[Xe] 4f10 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.9389,
		valence: 12,
		electronegativity: 1.22,
	},
	{
		number: 67,
		symbol: 'Ho',
		name: 'Holmium',
		atomicMass: 164.930332,
		row: 9,
		column: 13,
		subshellBlock: 'f',
		cpkHexColor: '00FF9C',
		electronicConfiguration: '[Xe] 4f11 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 6.0215,
		valence: 13,
		electronegativity: 1.23,
	},
	{
		number: 68,
		symbol: 'Er',
		name: 'Erbium',
		atomicMass: 167.2593,
		row: 9,
		column: 14,
		subshellBlock: 'f',
		cpkHexColor: '00E675',
		electronicConfiguration: '[Xe] 4f12 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 6.1077,
		valence: 14,
		electronegativity: 1.24,
	},
	{
		number: 69,
		symbol: 'Tm',
		name: 'Thulium',
		atomicMass: 168.934222,
		row: 9,
		column: 15,
		subshellBlock: 'f',
		cpkHexColor: '00D452',
		electronicConfiguration: '[Xe] 4f13 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 6.1843,
		valence: 15,
		electronegativity: 1.25,
	},
	{
		number: 70,
		symbol: 'Yb',
		name: 'Ytterbium',
		atomicMass: 173.0451,
		row: 9,
		column: 16,
		subshellBlock: 'f',
		cpkHexColor: '00BF38',
		electronicConfiguration: '[Xe] 4f14 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 6.2542,
		valence: 16,
		electronegativity: 1.1,
	},
	{
		number: 71,
		symbol: 'Lu',
		name: 'Lutetium',
		atomicMass: 174.96681,
		row: 9,
		column: 17,
		subshellBlock: 'f',
		cpkHexColor: '00AB24',
		electronicConfiguration: '[Xe] 4f14 5d1 6s2',
		standardState: 'solid',
		chemicalFamily: 'lanthanoid',
		metallicity: 'metal',
		ionizationEnergy: 5.4259,
		valence: 17,
		electronegativity: 1.27,
	},
	{
		number: 72,
		symbol: 'Hf',
		name: 'Hafnium',
		atomicMass: 178.492,
		row: 6,
		column: 4,
		subshellBlock: 'd',
		cpkHexColor: '4DC2FF',
		electronicConfiguration: '[Xe] 4f14 5d2 6s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.8251,
		valence: 4,
		electronegativity: 1.3,
	},
	{
		number: 73,
		symbol: 'Ta',
		name: 'Tantalum',
		atomicMass: 180.947882,
		row: 6,
		column: 5,
		subshellBlock: 'd',
		cpkHexColor: '4DA6FF',
		electronicConfiguration: '[Xe] 4f14 5d3 6s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.5496,
		valence: 5,
		electronegativity: 1.5,
	},
	{
		number: 74,
		symbol: 'W',
		name: 'Tungsten',
		atomicMass: 183.841,
		row: 6,
		column: 6,
		subshellBlock: 'd',
		cpkHexColor: '2194D6',
		electronicConfiguration: '[Xe] 4f14 5d4 6s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.864,
		valence: 6,
		electronegativity: 2.36,
	},
	{
		number: 75,
		symbol: 'Re',
		name: 'Rhenium',
		atomicMass: 186.2071,
		row: 6,
		column: 7,
		subshellBlock: 'd',
		cpkHexColor: '267DAB',
		electronicConfiguration: '[Xe] 4f14 5d5 6s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 7.8335,
		valence: 7,
		electronegativity: 1.9,
	},
	{
		number: 76,
		symbol: 'Os',
		name: 'Osmium',
		atomicMass: 190.233,
		row: 6,
		column: 8,
		subshellBlock: 'd',
		cpkHexColor: 266696,
		electronicConfiguration: '[Xe] 4f14 5d6 6s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 8.4382,
		valence: 8,
		electronegativity: 2.2,
	},
	{
		number: 77,
		symbol: 'Ir',
		name: 'Iridium',
		atomicMass: 192.2173,
		row: 6,
		column: 9,
		subshellBlock: 'd',
		cpkHexColor: 175487,
		electronicConfiguration: '[Xe] 4f14 5d7 6s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 8.967,
		valence: 9,
		electronegativity: 2.20,
	},
	{
		number: 78,
		symbol: 'Pt',
		name: 'Platinum',
		atomicMass: 195.0849,
		row: 6,
		column: 10,
		subshellBlock: 'd',
		cpkHexColor: 'D0D0E0',
		electronicConfiguration: '[Xe] 4f14 5d9 6s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 8.9588,
		valence: 10,
		electronegativity: 2.28,
	},
	{
		number: 79,
		symbol: 'Au',
		name: 'Gold',
		atomicMass: 196.9665695,
		row: 6,
		column: 11,
		subshellBlock: 'd',
		cpkHexColor: 'FFD123',
		electronicConfiguration: '[Xe] 4f14 5d10 6s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 9.2255,
		valence: 11,
		electronegativity: 2.54,
	},
	{
		number: 80,
		symbol: 'Hg',
		name: 'Mercury',
		atomicMass: 200.5923,
		row: 6,
		column: 12,
		subshellBlock: 'd',
		cpkHexColor: 'B8B8D0',
		electronicConfiguration: '[Xe] 4f14 5d10 6s2',
		standardState: 'liquid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 10.4375,
		valence: 12,
		electronegativity: 2.00,
	},
	{
		number: 81,
		symbol: 'Tl',
		name: 'Thallium',
		atomicMass: 204.38,
		row: 6,
		column: 13,
		subshellBlock: 'p',
		cpkHexColor: 'A6544D',
		electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p1',
		standardState: 'solid',
		chemicalFamily: 'metal',
		metallicity: 'metal',
		ionizationEnergy: 6.1082,
		valence: 13,
		electronegativity: 1.62,
	},
	{
		number: 82,
		symbol: 'Pb',
		name: 'Lead',
		atomicMass: 207.21,
		row: 6,
		column: 14,
		subshellBlock: 'p',
		cpkHexColor: 575961,
		electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p2',
		standardState: 'solid',
		chemicalFamily: 'metal',
		metallicity: 'metal',
		ionizationEnergy: 7.4167,
		valence: 14,
		electronegativity: 2.33,
	},
	{
		number: 83,
		symbol: 'Bi',
		name: 'Bismuth',
		atomicMass: 208.980401,
		row: 6,
		column: 15,
		subshellBlock: 'p',
		cpkHexColor: '9E4FB5',
		electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p3',
		standardState: 'solid',
		chemicalFamily: 'metal',
		metallicity: 'metal',
		ionizationEnergy: 7.2856,
		valence: 15,
		electronegativity: 2.02,
	},
	{
		number: 84,
		symbol: 'Po',
		name: 'Polonium',
		atomicMass: 209,
		row: 6,
		column: 16,
		subshellBlock: 'p',
		cpkHexColor: 'AB5C00',
		electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p4',
		standardState: 'solid',
		chemicalFamily: 'metalloid',
		metallicity: 'metal',
		ionizationEnergy: 8.414,
		valence: 16,
		electronegativity: 2.0,
	},
	{
		number: 85,
		symbol: 'At',
		name: 'Astatine',
		atomicMass: 210,
		row: 6,
		column: 17,
		subshellBlock: 'p',
		cpkHexColor: '754F45',
		electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p5',
		standardState: 'solid',
		chemicalFamily: 'halogen',
		metallicity: 'metalloid',
		ionizationEnergy: 9.3,
		valence: 17,
		electronegativity: 2.2,
	},
	{
		number: 86,
		symbol: 'Rn',
		name: 'Radon',
		atomicMass: 222,
		row: 6,
		column: 18,
		subshellBlock: 'p',
		cpkHexColor: 428296,
		electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p6',
		standardState: 'gas',
		chemicalFamily: 'noble-gas',
		metallicity: 'nonmetal',
		ionizationEnergy: 10.7485,
		valence: 18,
		electronegativity: null,
	},
	{
		number: 87,
		symbol: 'Fr',
		name: 'Francium',
		atomicMass: 223,
		row: 7,
		column: 1,
		subshellBlock: 's',
		cpkHexColor: 420066,
		electronicConfiguration: '[Rn] 7s1',
		standardState: 'solid',
		chemicalFamily: 'alkali-metal',
		metallicity: 'metal',
		ionizationEnergy: 4.0727,
		valence: 1,
		electronegativity: 0.7,
	},
	{
		number: 88,
		symbol: 'Ra',
		name: 'Radium',
		atomicMass: 226,
		row: 7,
		column: 2,
		subshellBlock: 's',
		cpkHexColor: '007D00',
		electronicConfiguration: '[Rn] 7s2',
		standardState: 'solid',
		chemicalFamily: 'alkaline-earth-metal',
		metallicity: 'metal',
		ionizationEnergy: 5.2784,
		valence: 2,
		electronegativity: 0.9,
	},
	{
		number: 89,
		symbol: 'Ac',
		name: 'Actinium',
		atomicMass: 227,
		row: 7,
		column: 3,
		subshellBlock: 'd',
		cpkHexColor: '70ABFA',
		electronicConfiguration: '[Rn] 6d1 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 5.17,
		valence: 3,
		electronegativity: 1.1,
	},
	{
		number: 90,
		symbol: 'Th',
		name: 'Thorium',
		atomicMass: 232.03774,
		row: 10,
		column: 4,
		subshellBlock: 'f',
		cpkHexColor: '00BAFF',
		electronicConfiguration: '[Rn] 6d2 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.3067,
		valence: 4,
		electronegativity: 1.3,
	},
	{
		number: 91,
		symbol: 'Pa',
		name: 'Protactinium',
		atomicMass: 231.035882,
		row: 10,
		column: 5,
		subshellBlock: 'f',
		cpkHexColor: '00A1FF',
		electronicConfiguration: '[Rn] 5f2 6d1 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 5.89,
		valence: 5,
		electronegativity: 1.5,
	},
	{
		number: 92,
		symbol: 'U',
		name: 'Uranium',
		atomicMass: 238.028913,
		row: 10,
		column: 6,
		subshellBlock: 'f',
		cpkHexColor: '008FFF',
		electronicConfiguration: '[Rn] 5f3 6d1 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.1941,
		valence: 6,
		electronegativity: 1.38,
	},
	{
		number: 93,
		symbol: 'Np',
		name: 'Neptunium',
		atomicMass: 237,
		row: 10,
		column: 7,
		subshellBlock: 'f',
		cpkHexColor: '0080FF',
		electronicConfiguration: '[Rn] 5f4 6d1 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.2657,
		valence: 7,
		electronegativity: 1.36,
	},
	{
		number: 94,
		symbol: 'Pu',
		name: 'Plutonium',
		atomicMass: 244,
		row: 10,
		column: 8,
		subshellBlock: 'f',
		cpkHexColor: '006BFF',
		electronicConfiguration: '[Rn] 5f6 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.0262,
		valence: 8,
		electronegativity: 1.28,
	},
	{
		number: 95,
		symbol: 'Am',
		name: 'Americium',
		atomicMass: 243,
		row: 10,
		column: 9,
		subshellBlock: 'f',
		cpkHexColor: '545CF2',
		electronicConfiguration: '[Rn] 5f7 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 5.9738,
		valence: 9,
		electronegativity: 1.3,
	},
	{
		number: 96,
		symbol: 'Cm',
		name: 'Curium',
		atomicMass: 247,
		row: 10,
		column: 10,
		subshellBlock: 'f',
		cpkHexColor: '785CE3',
		electronicConfiguration: '[Rn] 5f7 6d1 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 5.9915,
		valence: 10,
		electronegativity: 1.3,
	},
	{
		number: 97,
		symbol: 'Bk',
		name: 'Berkelium',
		atomicMass: 247,
		row: 10,
		column: 11,
		subshellBlock: 'f',
		cpkHexColor: '8A4FE3',
		electronicConfiguration: '[Rn] 5f9 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.1979,
		valence: 11,
		electronegativity: 1.3,
	},
	{
		number: 98,
		symbol: 'Cf',
		name: 'Californium',
		atomicMass: 251,
		row: 10,
		column: 12,
		subshellBlock: 'f',
		cpkHexColor: 'A136D4',
		electronicConfiguration: '[Rn] 5f10 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.2817,
		valence: 12,
		electronegativity: 1.3,
	},
	{
		number: 99,
		symbol: 'Es',
		name: 'Einsteinium',
		atomicMass: 252,
		row: 10,
		column: 13,
		subshellBlock: 'f',
		cpkHexColor: 'B31FD4',
		electronicConfiguration: '[Rn] 5f11 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.42,
		valence: 13,
		electronegativity: 1.3,
	},
	{
		number: 100,
		symbol: 'Fm',
		name: 'Fermium',
		atomicMass: 257,
		row: 10,
		column: 14,
		subshellBlock: 'f',
		cpkHexColor: 'B31FBA',
		electronicConfiguration: '[Rn] 5f12 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.5,
		valence: 14,
		electronegativity: 1.3,
	},
	{
		number: 101,
		symbol: 'Md',
		name: 'Mendelevium',
		atomicMass: 258,
		row: 10,
		column: 15,
		subshellBlock: 'f',
		cpkHexColor: 'B30DA6',
		electronicConfiguration: '[Rn] 5f13 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.58,
		valence: 15,
		electronegativity: 1.3,
	},
	{
		number: 102,
		symbol: 'No',
		name: 'Nobelium',
		atomicMass: 259,
		row: 10,
		column: 16,
		subshellBlock: 'f',
		cpkHexColor: 'BD0D87',
		electronicConfiguration: '[Rn] 5f14 7s2',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 6.65,
		valence: 16,
		electronegativity: 1.3,
	},
	{
		number: 103,
		symbol: 'Lr',
		name: 'Lawrencium',
		atomicMass: 266,
		row: 10,
		column: 17,
		subshellBlock: 'f',
		cpkHexColor: 'C70066',
		electronicConfiguration: '[Rn] 5f14 7s2 7p1',
		standardState: 'solid',
		chemicalFamily: 'actinoid',
		metallicity: 'metal',
		ionizationEnergy: 4.9,
		valence: 17,
		electronegativity: 1.3,
	},
	{
		number: 104,
		symbol: 'Rf',
		name: 'Rutherfordium',
		atomicMass: 267,
		row: 7,
		column: 4,
		subshellBlock: 'd',
		cpkHexColor: 'CC0059',
		electronicConfiguration: '[Rn] 5f14 6d2 7s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.0,
		valence: 4,
		electronegativity: 1.3,
	},
	{
		number: 105,
		symbol: 'Db',
		name: 'Dubnium',
		atomicMass: 268,
		row: 7,
		column: 5,
		subshellBlock: 'd',
		cpkHexColor: 'D1004F',
		electronicConfiguration: '[Rn] 5f14 6d3 7s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.0,
		valence: 5,
		electronegativity: 1.3,
	},
	{
		number: 106,
		symbol: 'Sg',
		name: 'Seaborgium',
		atomicMass: 269,
		row: 7,
		column: 6,
		subshellBlock: 'd',
		cpkHexColor: 'D90045',
		electronicConfiguration: '[Rn] 5f14 6d4 7s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.1,
		valence: 6,
		electronegativity: 1.3,

	},
	{
		number: 107,
		symbol: 'Bh',
		name: 'Bohrium',
		atomicMass: 270,
		row: 7,
		column: 7,
		subshellBlock: 'd',
		cpkHexColor: 'E00038',
		electronicConfiguration: '[Rn] 5f14 6d5 7s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.3,
		valence: 7,
		electronegativity: 1.3,
	},
	{
		number: 108,
		symbol: 'Hs',
		name: 'Hassium',
		atomicMass: 269,
		row: 7,
		column: 8,
		subshellBlock: 'd',
		cpkHexColor: 'E6002E',
		electronicConfiguration: '[Rn] 5f14 6d6 7s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.3,
		valence: 8,
		electronegativity: 1.3,
	},
	{
		number: 109,
		symbol: 'Mt',
		name: 'Meitnerium',
		atomicMass: 278,
		row: 7,
		column: 9,
		subshellBlock: 'd',
		cpkHexColor: 'EB0026',
		electronicConfiguration: '[Rn] 5f14 6d7 7s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'unspecified',
		ionizationEnergy: 6.3,
		valence: 9,
		electronegativity: 1.3,
	},
	{
		number: 110,
		symbol: 'Ds',
		name: 'Darmstadtium',
		atomicMass: 281,
		row: 7,
		column: 10,
		subshellBlock: 'd',
		cpkHexColor: 'EB0026',
		electronicConfiguration: '[Rn] 5f14 6d9 7s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'unspecified',
		ionizationEnergy: 6.3,
		valence: 10,
		electronegativity: 1.3,
	},
	{
		number: 111,
		symbol: 'Rg',
		name: 'Roentgenium',
		atomicMass: 282,
		row: 7,
		column: 11,
		subshellBlock: 'd',
		cpkHexColor: 'EB0026',
		electronicConfiguration: '[Rn] 5f14 6d10 7s1',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'unspecified',
		ionizationEnergy: 6.3,
		valence: 11,
		electronegativity: 1.3,

	},
	{
		number: 112,
		symbol: 'Cn',
		name: 'Copernicium',
		atomicMass: 285,
		row: 7,
		column: 12,
		subshellBlock: 'd',
		cpkHexColor: 'EB0026',
		electronicConfiguration: '[Rn] 5f14 6d10 7s2',
		standardState: 'solid',
		chemicalFamily: 'transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.3,
		valence: 12,
		electronegativity: 1.3,
	},
	// {
	// 	number: 113,
	// 	symbol: 'Nh',
	// 	name: 'Nihonium',
	// 	atomicMass: 286,
	// 	row: 7,
	// 	column: 13,
	// 	cpkHexColor: 'EB0026',
	// 	electronicConfiguration: '[Rn] 5f14 6d10 7s2 7p1',
	// 	standardState: 'solid',
	// 	chemicalFamily: 'post-transition-metal',
	// 	metallicity: 'metal',
	// 	ionizationEnergy: 6.3,
	// 	valence: 13,
	// 	electronegativity: 1.3,
	// },
	{
		number: 114,
		symbol: 'Fl',
		name: 'Flerovium',
		atomicMass: 289,
		row: 7,
		column: 14,
		subshellBlock: 'p',
		cpkHexColor: 'EB0026',
		electronicConfiguration: '[Rn] 5f14 6d10 7s2 7p2',
		standardState: 'solid',
		chemicalFamily: 'post-transition-metal',
		metallicity: 'metal',
		ionizationEnergy: 6.3,
		valence: 14,
		electronegativity: 1.3,
	},
	// {
	// 	number: 115,
	// 	symbol: 'Mc',
	// 	name: 'Moscovium',
	// 	atomicMass: 290,
	// 	row: 7,
	// 	column: 15,
	// 	cpkHexColor: 'EB0026',
	// 	electronicConfiguration: '[Rn] 5f14 6d10 7s2 7p3',
	// 	standardState: 'solid',
	// 	chemicalFamily: 'post-transition-metal',
	// 	metallicity: 'metal',
	// 	ionizationEnergy: 6.3,
	// 	valence: 15,
	// 	electronegativity: 1.3,
	// },
	{
		number: 116,
		symbol: 'Lv',
		name: 'Livermorium',
		atomicMass: 293,
		row: 7,
		column: 16,
		subshellBlock: 'p',
		cpkHexColor: 'EB0026',
		electronicConfiguration: '[Rn] 5f14 6d10 7s2 7p4',
		standardState: 'solid',
		chemicalFamily: 'post-transition-metal',
		metallicity: 'unspecified',
		ionizationEnergy: 6.3,
		valence: 16,
		electronegativity: 1.3,
	}
	// {
	// 	number: 117,
	// 	symbol: 'Ts',
	// 	name: 'Tennessine',
	// 	atomicMass: 294,
	// 	row: 7,
	// 	column: 17,
	// 	cpkHexColor: 'EB0026',
	// 	electronicConfiguration: '[Rn] 5f14 6d10 7s2 7p5',
	// 	standardState: 'solid',
	// 	chemicalFamily: 'post-transition-metal',
	// 	metallicity: 'metal',
	// 	ionizationEnergy: 6.3,
	// 	valence: 17,
	// 	electronegativity: 1.3,
	// },
	// {
	// 	number: 118,
	// 	symbol: 'Og',
	// 	name: 'Oganesson',
	// 	atomicMass: 294,
	// 	row: 7,
	// 	column: 18,
	// 	cpkHexColor: 'EB0026',
	// 	electronicConfiguration: '[Rn] 5f14 6d10 7s2 7p6',
	// 	standardState: 'solid',
	// 	chemicalFamily: 'noble-gas',
	// 	metallicity: 'nonmetal',
	// 	ionizationEnergy: 6.3,
	// 	valence: 18,
	// 	electronegativity: 1.3,
	// }
];

type colorSchemeGroup = Record<
	string,
	{
		name: string;
		color: string;
	}
>;

type ColorSchemes = Record<
	string,
	{
		name: string;
		group: colorSchemeGroup;
	}
>;

export const colorSchemes: ColorSchemes = {
	subshellBlock: {
		name: 'Subshell Blocks',
		group: {
			s: {
				name: 'S',
				color: '#523E1B'
			},
			p: {
				name: 'P',
				color: '#2A4165'
			},
			d: {
				name: 'D',
				color: '#425D58'
			},
			f: {
				name: 'F',
				color: '#622E39'
			}
		}
	},
	chemicalFamily: {
		name: 'Chemical Family',
		group: {
			actinoid: {
				name: 'Actinoid',
				color: '#613B28'
			},
			'alkali-metal': {
				name: 'Alkali Metal',
				color: '#244D57'
			},
			'alkaline-earth-metal': {
				name: 'Alkaline Earth Metal',
				color: '#70414B'
			},
			halogen: {
				name: 'Halogen',
				color: '#701470' // a faire
			},
			lanthanoid: {
				name: 'Lanthanoid',
				color: '#3D5273'
			},
			metal: {
				name: 'Metal',
				color: '#622E39'
			},
			metalloid: {
				name: 'Metalloid',
				color: '#523E1B'
			},
			'noble-gas': {
				name: 'Noble Gas',
				color: '#7D297D'
			},
			nonmetal: {
				name: 'Nonmetal',
				color: '#2A4165'
			},
			'post-transition-metal': {
				name: 'Post Transition Metal',
				color: '#2F4D47'
			},
			'transition-metal': {
				name: 'Transition Metal',
				color: '#425D58'
			}
		}
	},
	standardState: {
		name: 'Standard State',
		group: {
			gas: {
				name: 'Gas',
				color: '#622E39'
			},
			liquid: {
				name: 'Liquid',
				color: '#2A4165'
			},
			solid: {
				name: 'Solid',
				color: '#523E1B'
			}
		}
	},
	metallicity: {
		name: 'Metallicity',
		group: {
			metal: {
				name: 'Metal',
				color: '#622E39'
			},
			metalloid: {
				name: 'Metalloid',
				color: '#523E1B'
			},
			nonmetal: {
				name: 'Nonmetal',
				color: '#2A4165'
			},
			unspecified: {
				name: 'Unspecified',
				color: '#333'
			}
		}
	},
	electronegativity: {
		name: 'Electronegativity',
		group: {
			high: {
				name: 'High',
				color: 'rgb(125, 125, 255)'
			},
			medium: {
				name: 'Medium',
				color: 'rgb(62, 62, 125)'
			},
			low: {
				name: 'Null',
				color: '#000'
			}
		}
	},
	// blocks: {
	// 	name: 'Blocks',
	// 	group: {
	// 		sBlock: {
	// 			name: 'S-Block',
	// 			color: '#7F7F7F'
	// 		},
	// 		pBlock: {
	// 			name: 'P-Block',
	// 			color: '#A52A2A'
	// 		},
	// 		dBlock: {
	// 			name: 'D-Block',
	// 			color: '#008B8B'
	// 		},
	// 		fBlock: {
	// 			name: 'F-Block',
	// 			color: '#8B4513'
	// 		}
	// 	}
	// },
	// radioactivity: {
	// 	name: 'Radioactivity',
	// 	group: {
	// 		radioactive: {
	// 			name: 'Radioactive',
	// 			color: '#FF4500'
	// 		},
	// 		nonRadioactive: {
	// 			name: 'Non-Radioactive',
	// 			color: '#00FF00'
	// 		}
	// 	}
	// }
};
